version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"   # LocalStack main API port
      - "4572:4572"   # S3 port
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  s3client:
    image: amazon/aws-cli:latest
    container_name: s3client
    entrypoint: [ "sh", "-c", "until aws --endpoint-url=http://localstack:4566 s3 ls; do sleep 1; done" ]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    volumes:
      - "./data:/data"
